import time
x = str(input("enter a word and ill tell you how many vowels there are:"))
s = len(x)
time.sleep(3)
print("Hmm, the length is", s)
v = x.count("a")
r = x.count("e")
t = x.count("i")
f = x.count("o")
y = x.count("u")
print("amount of A's:", v)
time.sleep(3)
print("amount of E's:", r)
time.sleep(3)
print("there are", t , "I's")
time.sleep(3)
print(f, "O's...")
time.sleep(3)
print("and", y, "U's")
time.sleep(5)
print ("your word was", x)
time.sleep(5)
print("the length was:", s)
time.sleep(5)
print("List of vowels:")
print("A:",v , "E:", r, "I:", t, "O:", f, "U:", y)

